### ISSUE TITLE
Missing images for dogs, cats, and bottles in folder PASCAL_VOC_2012/human_attention_overlay

### ISSUE THREAD

**Issue by nobelliaw** [SinaMohseni/ML-Interpretability-Evaluation-Benchmark#1]
Hi, I don't find the images for dogs, cats, and bottles in directory PASCAL_VOC_2012/human_attention_overlay, but their masks are there in another directories. Can you please upload them?

**Comment by SinaMohseni** [comment]
sorry for the missing files. all three folders are added now. plus the original raw images for each category.
